-- Initial PostgreSQL schema (ported from the SQLite schema + multi-world support).
-- Timestamps stay as Unix epoch seconds (DOUBLE PRECISION) to match the game code.

CREATE TABLE worlds (
    id INTEGER PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at DOUBLE PRECISION NOT NULL
);

INSERT INTO worlds (id, code, name, status, created_at) VALUES
    (1, 'world1', 'Мир 1', 'open', extract(epoch FROM now())),
    (2, 'world2', 'Мир 2', 'open', extract(epoch FROM now())),
    (3, 'world3', 'Мир 3', 'open', extract(epoch FROM now())),
    (4, 'world4', 'Мир 4', 'open', extract(epoch FROM now()));

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    created_at DOUBLE PRECISION NOT NULL,
    last_login_at DOUBLE PRECISION
);

-- Owner of server-side NPC characters (tavern bartender, chat bots). Cannot log in.
INSERT INTO users (id, username, password_hash, role, created_at)
VALUES (0, '__system__', '!', 'system', extract(epoch FROM now()));

CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    world_id INTEGER NOT NULL REFERENCES worlds(id),
    created_at DOUBLE PRECISION NOT NULL,
    last_seen_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_last_seen ON sessions(last_seen_at);

CREATE TABLE characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    world_id INTEGER NOT NULL REFERENCES worlds(id),
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'warrior',
    level INTEGER NOT NULL DEFAULT 1,
    xp BIGINT NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL,
    max_hp INTEGER NOT NULL,
    mp INTEGER NOT NULL DEFAULT 50,
    max_mp INTEGER NOT NULL DEFAULT 50,
    stats_json TEXT NOT NULL,
    stat_points INTEGER NOT NULL DEFAULT 6,
    zone TEXT NOT NULL DEFAULT 'town',
    copper BIGINT NOT NULL DEFAULT 0,
    silver BIGINT NOT NULL DEFAULT 0,
    gold BIGINT NOT NULL DEFAULT 0,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_characters_user ON characters(user_id);
CREATE INDEX idx_characters_world ON characters(world_id);
-- One player character per account in each world; NPCs (system user) are exempt.
CREATE UNIQUE INDEX uq_characters_user_world ON characters(user_id, world_id) WHERE user_id <> 0;
CREATE UNIQUE INDEX uq_characters_world_name ON characters(world_id, lower(name)) WHERE user_id <> 0;

CREATE FUNCTION forbid_character_world_change() RETURNS trigger AS $$
BEGIN
    IF NEW.world_id IS DISTINCT FROM OLD.world_id THEN
        RAISE EXCEPTION 'characters.world_id is immutable';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_characters_world_immutable
    BEFORE UPDATE OF world_id ON characters
    FOR EACH ROW EXECUTE FUNCTION forbid_character_world_change();

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id INTEGER NOT NULL REFERENCES worlds(id),
    location TEXT NOT NULL,
    sender_character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    recipient_character_id TEXT,
    text TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    deleted_at DOUBLE PRECISION,
    deleted_by BIGINT
);
CREATE INDEX idx_chat_messages_location_time ON chat_messages(world_id, location, created_at, id);

CREATE TABLE chat_reads (
    character_id BIGINT NOT NULL,
    location TEXT NOT NULL,
    last_read_message_id BIGINT NOT NULL DEFAULT 0,
    last_read_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (character_id, location)
);

CREATE TABLE chat_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    reporter_character_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE chat_mutes (
    character_id BIGINT NOT NULL,
    muted_character_id BIGINT NOT NULL,
    expires_at DOUBLE PRECISION,
    PRIMARY KEY (character_id, muted_character_id)
);

CREATE TABLE active_battles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    opponent_id BIGINT NOT NULL,
    battle_data TEXT NOT NULL,
    player_afk INTEGER NOT NULL DEFAULT 0,
    opponent_afk INTEGER NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE battle_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    opponent_id BIGINT NOT NULL,
    battle_data TEXT NOT NULL,
    player_afk INTEGER NOT NULL DEFAULT 0,
    opponent_afk INTEGER NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_battle_logs_expires_at ON battle_logs(expires_at);

CREATE TABLE drinks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    price_copper INTEGER NOT NULL DEFAULT 0,
    price_silver INTEGER NOT NULL DEFAULT 0,
    price_gold INTEGER NOT NULL DEFAULT 0,
    effect TEXT NOT NULL,
    effect_value INTEGER NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE character_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    drink_id BIGINT NOT NULL REFERENCES drinks(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    UNIQUE (character_id, drink_id)
);

CREATE TABLE character_card_collection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    card_key TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    slot_index INTEGER NOT NULL,
    acquired_at DOUBLE PRECISION NOT NULL,
    UNIQUE (character_id, card_key),
    UNIQUE (character_id, slot_index)
);
CREATE INDEX idx_card_collection_character ON character_card_collection(character_id);

CREATE TABLE items_catalog (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    item_type TEXT NOT NULL,
    rarity TEXT NOT NULL,
    weight DOUBLE PRECISION NOT NULL,
    price INTEGER NOT NULL,
    description TEXT,
    can_use INTEGER NOT NULL DEFAULT 0,
    effects_json TEXT,
    bonuses_json TEXT,
    icon TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    equip_slot TEXT
);

CREATE TABLE character_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES items_catalog(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    slot_index INTEGER NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE (character_id, slot_index)
);
CREATE INDEX idx_items_character ON character_items(character_id);

CREATE TABLE character_item_grants (
    character_id BIGINT PRIMARY KEY REFERENCES characters(id) ON DELETE CASCADE,
    starter_kit_at DOUBLE PRECISION NOT NULL
);

CREATE TABLE character_equipment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    slot TEXT NOT NULL,
    item_id INTEGER NOT NULL REFERENCES items_catalog(id),
    equipped_at DOUBLE PRECISION NOT NULL,
    UNIQUE (character_id, slot)
);
CREATE INDEX idx_equipment_character ON character_equipment(character_id);

CREATE TABLE character_storage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    storage_type TEXT NOT NULL,
    item_id INTEGER NOT NULL REFERENCES items_catalog(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    slot_index INTEGER,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE (character_id, storage_type, item_id, slot_index)
);
CREATE INDEX idx_storage_character ON character_storage(character_id);

CREATE TABLE character_decks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 0,
    cards_json TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX idx_decks_character ON character_decks(character_id);

CREATE TABLE battle_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    battle_id BIGINT,
    item_id INTEGER NOT NULL REFERENCES items_catalog(id),
    quantity INTEGER NOT NULL,
    claimed INTEGER NOT NULL DEFAULT 0,
    created_at DOUBLE PRECISION NOT NULL,
    claimed_at DOUBLE PRECISION
);
CREATE INDEX idx_rewards_character ON battle_rewards(character_id);

CREATE TABLE farm_states (
    character_id BIGINT PRIMARY KEY REFERENCES characters(id) ON DELETE CASCADE,
    level INTEGER NOT NULL DEFAULT 1,
    cycle_start_time DOUBLE PRECISION NOT NULL,
    storage_wheat INTEGER NOT NULL DEFAULT 0,
    buffer_wheat INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE farm_worker_slots (
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    slot_index INTEGER NOT NULL,
    occupied INTEGER NOT NULL DEFAULT 0,
    worker_id TEXT,
    hire_time DOUBLE PRECISION,
    PRIMARY KEY (character_id, slot_index)
);
