CREATE TABLE stable_horses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id INTEGER NOT NULL,
    faction TEXT NOT NULL,
    building TEXT NOT NULL DEFAULT 'stable' CHECK (building = 'stable'),
    slot_index INTEGER NOT NULL CHECK (slot_index >= 0),
    name TEXT NOT NULL,
    breed TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Отдыхает',
    purchase_price_silver INTEGER NOT NULL CHECK (purchase_price_silver > 0),
    purchased_by BIGINT REFERENCES characters(id) ON DELETE SET NULL,
    purchased_at DOUBLE PRECISION NOT NULL,
    UNIQUE (world_id, faction, building, slot_index),
    FOREIGN KEY (world_id, faction, building)
        REFERENCES building_states(world_id, faction, building) ON DELETE CASCADE
);