CREATE TABLE forge_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
    faction TEXT NOT NULL,
    owner_character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES items_catalog(id),
    recipe_json JSONB NOT NULL,
    duration_seconds INTEGER NOT NULL CHECK (duration_seconds > 0),
    status TEXT NOT NULL CHECK (status IN ('queued', 'working', 'ready', 'claimed')),
    queued_at DOUBLE PRECISION NOT NULL,
    started_at DOUBLE PRECISION,
    completed_at DOUBLE PRECISION,
    claimed_at DOUBLE PRECISION
);

CREATE INDEX idx_forge_orders_queue
    ON forge_orders (world_id, faction, status, id)
    WHERE status IN ('queued', 'working');

CREATE INDEX idx_forge_orders_owner_warehouse
    ON forge_orders (owner_character_id, status, id)
    WHERE status = 'ready';
