INSERT INTO items_catalog
    (id, name, item_type, rarity, weight, price, description, can_use, effects_json,
     bonuses_json, icon, created_at, equip_slot)
VALUES
    (90, 'Старый серп', 'equipment', 'common', 1.0, 100,
     'Требование: Сила: 4. Увеличивает добычу пшеницы на 20%', 0,
     '{"requirements":{"strength":4},"damage":[1,1],"harvest_bonus":{"wheat":20},"two_handed":true}', NULL,
     'tool_sickle', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (91, 'Топор лесоруба', 'equipment', 'common', 1.0, 100,
     'Требование: Сила: 4. Увеличивает добычу древесины на 20%', 0,
     '{"requirements":{"strength":4},"damage":[1,1],"harvest_bonus":{"wood":20},"two_handed":true}', NULL,
     'tool_axe', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (92, 'Кирка', 'equipment', 'common', 1.0, 100,
     'Требование: Сила: 4. Увеличивает добычу железной руды, угля и камня на 20%', 0,
     '{"requirements":{"strength":4},"damage":[1,1],"harvest_bonus":{"iron_ore":20,"coal":20,"stone":20},"two_handed":true}', NULL,
     'tool_pickaxe', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (93, 'Разделочный нож', 'equipment', 'common', 1.0, 100,
     'Требование: Сила: 4. Увеличивает добычу кожи и мяса на 20%', 0,
     '{"requirements":{"strength":4},"damage":[1,1],"harvest_bonus":{"leather":20,"meat":20},"two_handed":true}', NULL,
     'tool_butcher_knife', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (23, 'Дубина', 'equipment', 'common', 5.0, 500,
     'Требование: Сила: 4. HP +20', 0,
     '{"requirements":{"strength":4},"damage":[3,10]}', '{"hp":20}',
     'weapon_club', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (24, 'Простой лук', 'equipment', 'common', 1.0, 400,
     'Требование: Ловкость: 6. Сила +2. Уворот: +5%', 0,
     '{"requirements":{"agility":6},"damage":[4,8],"two_handed":true,"dodge":5}', '{"strength":2,"dodge":5}',
     'weapon_bow', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (25, 'Деревянный посох', 'equipment', 'common', 2.0, 500,
     'Требование: Мудрость: 6, Интеллект: 4. MP +30', 0,
     '{"requirements":{"wisdom":6,"intellect":4},"damage":[1,4],"either_hand":true}', '{"mp":30}',
     'weapon_staff', EXTRACT(EPOCH FROM clock_timestamp()), 'weapon'),
    (39, 'Деревянный щит', 'equipment', 'common', 3.0, 300,
     'Требование: Сила: 4. HP +20. Блок: +5%', 0,
     '{"requirements":{"strength":4},"damage":[0,0],"block":5}', '{"hp":20,"block":5}',
     'shield_wooden', EXTRACT(EPOCH FROM clock_timestamp()), 'shield')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    item_type = EXCLUDED.item_type,
    rarity = EXCLUDED.rarity,
    weight = EXCLUDED.weight,
    price = EXCLUDED.price,
    description = EXCLUDED.description,
    can_use = EXCLUDED.can_use,
    effects_json = EXCLUDED.effects_json,
    bonuses_json = EXCLUDED.bonuses_json,
    icon = EXCLUDED.icon,
    equip_slot = EXCLUDED.equip_slot;
