CREATE TABLE city_population_state (
    world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
    faction TEXT NOT NULL,
    castle_level INTEGER NOT NULL DEFAULT 1 CHECK (castle_level >= 1),
    last_food_tick_at DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (world_id, faction)
);

CREATE TABLE city_citizens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id INTEGER NOT NULL,
    faction TEXT NOT NULL,
    ordinal INTEGER NOT NULL,
    name TEXT NOT NULL,
    satiety INTEGER NOT NULL DEFAULT 100 CHECK (satiety BETWEEN 0 AND 100),
    satiety_updated_at DOUBLE PRECISION NOT NULL DEFAULT 0,
    hunger_streak INTEGER NOT NULL DEFAULT 0 CHECK (hunger_streak >= 0),
    satisfaction TEXT NOT NULL DEFAULT 'satisfied'
        CHECK (satisfaction IN ('satisfied', 'irritated', 'starving')),
    job_building TEXT,
    job_slot INTEGER,
    working BOOLEAN NOT NULL DEFAULT FALSE,
    arrival_at DOUBLE PRECISION,
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE (world_id, faction, ordinal),
    FOREIGN KEY (world_id, faction)
        REFERENCES city_population_state(world_id, faction) ON DELETE CASCADE
);

INSERT INTO city_population_state (world_id, faction, castle_level, last_food_tick_at)
SELECT id, 'light', 1, floor(extract(epoch FROM clock_timestamp()) / 3600) * 3600
FROM worlds
ON CONFLICT (world_id, faction) DO NOTHING;

INSERT INTO city_citizens
    (world_id, faction, ordinal, name, satiety, created_at)
SELECT state.world_id, state.faction, citizen.ordinal,
       'Горожанин ' || citizen.ordinal, 100, extract(epoch FROM clock_timestamp())
FROM city_population_state state
CROSS JOIN generate_series(1, 4) AS citizen(ordinal)
ON CONFLICT (world_id, faction, ordinal) DO NOTHING;