CREATE TABLE transport_convoys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
    faction TEXT NOT NULL,
    cart_id TEXT NOT NULL,
    cart_grade INTEGER NOT NULL CHECK (cart_grade >= 1),
    driver_citizen_id BIGINT NOT NULL REFERENCES city_citizens(id) ON DELETE RESTRICT,
    destination_building_id TEXT NOT NULL,
    cargo_json JSONB NOT NULL CHECK (jsonb_typeof(cargo_json) = 'array'),
    cargo_weight_kg NUMERIC(10, 2) NOT NULL CHECK (cargo_weight_kg > 0),
    capacity_kg INTEGER NOT NULL CHECK (capacity_kg > 0),
    travel_seconds INTEGER NOT NULL CHECK (travel_seconds > 0),
    started_at DOUBLE PRECISION NOT NULL,
    arrival_at DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL DEFAULT 'outbound'
        CHECK (status IN ('outbound', 'blocked', 'arrived')),
    delivered_quantity INTEGER NOT NULL DEFAULT 0 CHECK (delivered_quantity >= 0),
    started_by BIGINT REFERENCES characters(id) ON DELETE SET NULL,
    created_at DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX transport_convoys_active_cart
    ON transport_convoys (world_id, faction, cart_id) WHERE status IN ('outbound', 'blocked');
CREATE UNIQUE INDEX transport_convoys_active_driver
    ON transport_convoys (world_id, faction, driver_citizen_id) WHERE status IN ('outbound', 'blocked');
CREATE INDEX transport_convoys_world_status_arrival
    ON transport_convoys (world_id, faction, status, arrival_at);

CREATE TABLE transport_convoy_horses (
    convoy_id BIGINT NOT NULL REFERENCES transport_convoys(id) ON DELETE CASCADE,
    horse_id BIGINT NOT NULL REFERENCES stable_horses(id) ON DELETE RESTRICT,
    slot_index INTEGER NOT NULL CHECK (slot_index >= 0),
    PRIMARY KEY (convoy_id, horse_id),
    UNIQUE (convoy_id, slot_index)
);
