CREATE TABLE battle_archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    world_id INTEGER NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
    battle_key TEXT NOT NULL,
    player_character_id BIGINT REFERENCES characters(id) ON DELETE SET NULL,
    opponent_character_id BIGINT REFERENCES characters(id) ON DELETE SET NULL,
    player_name TEXT NOT NULL,
    opponent_name TEXT NOT NULL,
    player_level INTEGER NOT NULL CHECK (player_level >= 1),
    opponent_level INTEGER NOT NULL CHECK (opponent_level >= 1),
    winner_name TEXT NOT NULL,
    outcome TEXT NOT NULL CHECK (outcome IN ('win', 'draw', 'loss')),
    turns INTEGER NOT NULL DEFAULT 0 CHECK (turns >= 0),
    replay_json JSONB NOT NULL CHECK (jsonb_typeof(replay_json) = 'object'),
    created_at DOUBLE PRECISION NOT NULL,
    UNIQUE (world_id, battle_key)
);

CREATE INDEX battle_archive_world_created
    ON battle_archive (world_id, created_at DESC, id DESC);